### ISSUE TITLE
allow for crypto specific configuration templates

### ISSUE THREAD

**Issue by masternodes** [masternodes/vps#1]
**Rationale**
Some cryptos have slightly different configuration files than others. While it was always the goal to provide a generic solution, the possibility to integrate custom templates should be trivially to implement. 

**Implementation**
Change the "create_mn_configuration" to check for the existance of an existing coin template and use that instead. Generate a default (as it is now) if not.

***ARC example.***

In _arcticcoin.conf_, the default config should be

```
server=1
listen=1
daemon=1
goldminenode=1 
goldminenodeprivkey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB7XXX 
externalip=141.231.184.34
```
instead of 
```
server=1
listen=1
daemon=1
masternodeprivkey=6vzaXXXXXXXXXXXXXXXXXXXXXXXXXXXXB7USLp 
```

**Comment by marsmensch** [comment]
Done. If the script finds a specific configuration in the respective coins folder, this is used instead of the default configuration. ARC and MEME received those first. 

To adapt these configuration templates, edit eg 

> conf/arc/arc.conf
