### ISSUE TITLE
Does Pure work with IPv6?

### ISSUE THREAD

**Issue by technoshaman7777** [masternodes/vps#100]
Hi, I followed all instructions to setup two Pure Masternodes on Vultr using IPv6. My first node appears to be running on VPS, but does not show up in masternode list. The 2nd node does not run, and also doesn't show up. 

I noticed that no other Pure masternodes online, and thought that maybe I should have used IPv4. Is that correct? Does current NodeMaster script work on IPv4 if I pay for the extra static IP? Any other instructions that you can provide?

I really appreciate the work you have put into this and I hope you, or a fellow community member, can help me out.

**Comment by marsmensch** [comment]
Hello! The script does work w/ IPv4. To enable that, just add the parameter "-n 4" to install.sh and fill in the IP address in the individual config files.
