### ISSUE TITLE
Error when running for Gobyte

### ISSUE THREAD

**Issue by tokenlauncher** [masternodes/vps#101]
Hello, your supported coin list has GBX on it, but I am getting an error when I run it. 

./install.sh -p gbx -c 3
./install.sh: line 116: syntax error near unexpected token `>'
./install.sh: line 116: `    add-apt-repository -yu ppa:bitcoin/bitcoin  &>> ${SCRIPT_LOGFILE}'

Thank you for creating this and any help you can provide. 

Brad

**Comment by tokenlauncher** [comment]
Is anybody here?

**Comment by marsmensch** [comment]
Resolved via 1:1 support
