### ISSUE TITLE
Why are libdb4.8-dev and libdb4.8++-dev removed? They are needed for other masternodes.

### ISSUE THREAD

**Issue by pioniere** [masternodes/vps#104]
When running install.sh on a Linux VPS, I notice that it removes libdb4.8-dev and libdb4.8++-dev, which includes libdb_cxx-4.8.so. 

Removing libdb4.8 (4.8.30-xenial4) ...
Removing libdb4.8++ (4.8.30-xenial4) ...

Why is this done? This library is needed by other masternodes I have running on my VPS. If the removal step is just for 'cleanup' purposes, please don't!

**Comment by marsmensch** [comment]
No packages are explicitely removed. apt-get autoremove is called during cleanup, which might be the culprint. Be aware that for masternodes, the version of libdb is mostly irrelevant. It is only important for the controller wallet and gui.

**Comment by pioniere** [comment]
On my VPS I have 2 masternodes that would not start until I re-installed libdb4.8. Not a big deal , but thought was something that should be mentioned (particularly since it might confuse users not familiar with Linux).

**Comment by marsmensch** [comment]
Commented the autoremove call for now since the storage gain is small. Fixed in 28d0f99a7d5f955ef8eac453807803d4feff92c3
