### ISSUE TITLE
Unable to install masternode on Ubuntu Trusty (14.04)

### ISSUE THREAD

**Issue by tomeh100** [masternodes/vps#11]
Unable to install masternode on Ubuntu Trusty (14.04)

command used 
./runme.sh xcxt 1

read default config
Script version v0.6.3, you picked: xcxt
apply config file for xcxt
running installer script
Device "ens3" does not exist.
This script only supports ubuntu 16.04 LTS, exiting.

**Comment by marsmensch** [comment]
14.04 will not be supported because i strictly want _recent_ versions. Please use a 16.04 LTS VPS.
