### ISSUE TITLE
Script don't work

### ISSUE THREAD

**Issue by Jumperbillijumper** [masternodes/vps#110]
*************************************************************************************
Default interface doesn't exist, switching to eth0
* Validating network rules
* All good, we have a swap
* Package installation!
* Starting the compilation process for xsn, stay tuned
./install.sh: line 554: jp2a: command not found
* Checking out desired GIT tag: tags/v1.0.9
./install.sh: line 593: pv: command not found
./autogen.sh: 9: ./autogen.sh: autoreconf: not found
/root/vps/config/xsn/xsn.compile: line 5: ./configure: No such file or directory
/root/vps/config/xsn/xsn.compile: line 6: make: command not found
/root/vps/config/xsn/xsn.compile: line 7: make: command not found
COMPILATION FAILED! Please open an issue at https://github.com/masternodes/vps/issues. Thank you!
root@vmd26487:~/vps#

**Comment by marsmensch** [comment]
This can happen if there's a temporary hickup with the internet connection. Just verified the installation with the newest version version and it works. It's also possible, but not likely you cloned the repo exactly during one hour where i had a typo in the installer section :-/ Anyway, everything should work again now.
