### ISSUE TITLE
script doesn't work

### ISSUE THREAD

**Issue by Fearlesszz** [masternodes/vps#114]
Default interface doesn't exist, switching to eth0
* Validating network rules
* All good, we have a swap
* Package installation!
* Starting the compilation process for simple, stay tuned
* Checking out desired GIT tag: master
./install.sh: line 592: pv: command not found
./autogen.sh: 9: ./autogen.sh: autoreconf: not found
/home/masternode/simplevps/config/simple/simple.compile: line 5: ./configure: No                  such file or directory
/home/masternode/simplevps/config/simple/simple.compile: line 6: make: command n                 ot found
/home/masternode/simplevps/config/simple/simple.compile: line 7: make: command n                 ot found
COMPILATION FAILED! Please open an issue at https://github.com/masternodes/vps/i                 ssues. Thank you!
sed: can't read /etc/masternodes/simple_n1.conf: No such file or directory
sed: can't read /etc/masternodes/simple_n1.conf: No such file or directory
./simple_install.sh: line 75: /usr/local/bin/activate_masternodes_simple: No suc                 h file or directory
root@Mn1:/home/masternode/simplevps# https://github.com/masternodes/vps/i                        Thank you!

**Comment by marsmensch** [comment]
This can happen if there's a temporary hickup with the internet connection. Just verified the installation with the newest version version and it works. It's also possible, but not likely you cloned the repo exactly during one hour where i had a typo in the installer section :-/ Anyway, everything should work again now.
