### ISSUE TITLE
Permission denied. 

### ISSUE THREAD

**Issue by dev-x0** [masternodes/vps#150]
I have attempted to set up conf files for a coin called genesis-x. Previous coins which I have added (StakeCube coin and LightPayCoin) have worked fine but upon running the NodeMaster script I received an error with permission denied when it attempted to use the git tag. I have tried multiple different options but have reached a dead end it seems.

https://github.com/genesis-x/genesis-x

[genesisx.zip](https://github.com/masternodes/vps/files/2498677/genesisx.zip)

**Comment by marsmensch** [comment]
Fixed and commited your integration in this commit. Thanks! https://github.com/masternodes/vps/commit/5d841544057ca58df8d1397c6c3628eb414173c5
