### ISSUE TITLE
MonacoCoin Doesn't work

### ISSUE THREAD

**Issue by srikanth-v** [masternodes/vps#17]
Looks like it monacocoin masternode doesn't like the IPV6 format and the port number should be 24157 instead of 24156.

**Comment by marsmensch** [comment]
The new version of the script supports a new flag "-n 4". When this flag is used, ip addresses are pre-filled with placeholders and a link to the relevant docs how to manually add an ipv6 address is output.

Check the new documentation update here:
https://masternodes.github.io/vps/

P2P port is definitely 24156:
https://bitcointalk.org/index.php?topic=2083054.0

You can also adapt the configuration yourself, just edit the relevant config (eg "config/mona/mona.env") locally before running "install.sh" now.
