### ISSUE TITLE
Desire coin and Sentinel support

### ISSUE THREAD

**Issue by chikavladimir** [masternodes/vps#18]
Hello!

How can I configure Sentinel for Desire coin when I use masternodes system?

**Comment by marsmensch** [comment]
Desire is already supported. Check the new documentation: https://masternodes.github.io/vps/
What is Sentinel? Can you provide a link?

**Comment by chikavladimir** [comment]
https://github.com/ZonnCash/sentinel/releases/tag/v1.1.0-win64

Hello,  sentinel connect using desire.conf to daemon.  But now it work,  i
don't know how, i manually set path to config

Tnaks

13 нояб. 2017 г. 8:00 ПП пользователь "Florian Maier" <
notifications@github.com> написал:
