### ISSUE TITLE
Masternode.conf explanation

### ISSUE THREAD

**Issue by kopykatA** [masternodes/vps#19]
After using script in my vps for digitalprice multi masternodes, I used the suggested masternode.conf replacing of course with my own key txid and outputs. Looks like this>
dpriceMN01 [:2099::1]:9990 KEY TX OUTPUT
dpriceMN02 [:2099::2]:9990 KEY TX OUTPUT
dpriceMN03 [:2099::3]:9990 KEY TX OUTPUT
dpriceMN04 [:2099::4]:9990 KEY TX OUTPUT

(where KEY , TX and OUTPUT are my own)

How will my controller wallet know with what IP to connect to? There is no ip set. Only binds.

Thank you again for all your hard work.
Argy
(kopykat)

**Comment by marsmensch** [comment]
Which version of the script did you run (see output at start) and on which VPS provider? The IPv6 in your config addresses are obviously broken and that can never work. 

The latest version generates a template for you that should be pre-filled with the correct IP_Adresses like this

**1) When run on a system w/ IPv6 support:**
```
root@vultr:~/vps# cat /tmp/dprice_masternode.conf
dpriceMN1 [2001:19f0:8001:f10:2099::1]:9990 MASTERNODE_PRIVKEY_FOR_dpriceMN1 COLLATERAL_TX_FOR_dpriceMN1 OUTPUT_NO_FOR_dpriceMN1
root@vultr:~/vps#
```

**2) When run on a system w/ IPv4 support only:**
```
cat /tmp/dprice_masternode.conf
dpriceMN1 [#NEW_IPv4_ADDRESS_FOR_MASTERNODE_NUMBER:::1]:9990 MASTERNODE_PRIVKEY_FOR_dpriceMN1 COLLATERAL_TX_FOR_dpriceMN1 OUTPUT_NO_FOR_dpriceMN1
```

The latest version is v0.7.5, another bugfix update on the way for tonight.

**Comment by kopykatA** [comment]
I was running the latest you had in github (0.6.3 i think).
My vps provider is time4vps and i dont use. Ipv6. I ll try according to your info.
 If i wanna upgrade should i redo everything?
Recompile etc?

Sent from my iPhone

On 16 Nov 2017, at 11:15, Florian Maier <notifications@github.com<mailto:notifications@github.com>> wrote:


Which version of the script did you run (see output at start) and on which VPS provider? The IPv6 in your config addresses are obviously broken and that can never work.

The latest version generates a template for you that should be pre-filled with the correct IP_Adresses like this

1) When run on a system w/ IPv6 support:

root@vultr:~/vps# cat /tmp/dprice_masternode.conf
dpriceMN1 [2001:19f0:8001:f10:2099::1]:9990 MASTERNODE_PRIVKEY_FOR_dpriceMN1 COLLATERAL_TX_FOR_dpriceMN1 OUTPUT_NO_FOR_dpriceMN1
root@vultr:~/vps#


2) When run on a system w/ IPv4 support only:

cat /tmp/dprice_masternode.conf
dpriceMN1 [#NEW_IPv4_ADDRESS_FOR_MASTERNODE_NUMBER:::1]:9990 MASTERNODE_PRIVKEY_FOR_dpriceMN1 COLLATERAL_TX_FOR_dpriceMN1 OUTPUT_NO_FOR_dpriceMN1


The latest version is v0.7.5, another bugfix update on the way for tonight.

**Comment by kopykatA** [comment]
Ok, so my masternode.conf is now like this(all info are changed):
dpriceMN01 [12.12.12.99:::1]:9990 69GdpSUQKARdfoije908ut0wejrfop4dfopv89ut5pdkvgwer04 aer98fwje98jrpoifdjpoivdjfoivjsdofjpdfj0d9jfvopidjdfjkvpd90idfv 1
dpriceMN02 [12.12.12.99:::2]:9990 68SN89GdpSUQKARdfoije908ut0wejrfop3dfopv[pdkvgwer05 ber98fwje98jrpoifdjpoivdjfoivjsdofjpdfj0d9jfvopidjdjkvpd90idfv5 1
dpriceMN03 [12.12.12.99:::3]:9990 68tz9GdpSUQKARdfoije9t0wejrfopsdfopv67pdkvgwerrfg4w 4er98fwje98jrpoifdjpoivdjfivjsdofjdfj0d9jfvopidjdfjkvpdidfv2b26 0
dpriceMN04 [12.12.12.99:::4]:9990 6bGdpSUQKARdfoije908ut0wejrfopfghfopvfgerpdkvgwer0w aer98fwje98jrpoifdjpoivdjfoi0d9jfvopidjdfjkvpd90idfve76c37b5bd5 0
dpriceMN05 [12.12.12.99:::5]:9990 63dpSUQKARdfoije908ut0wejrfop[dfopv[pdkvgwepohujr0w aer98fwje98jrp9ipoivdjfoivjsdo9jfvpidjdfjkvpd90idfva7e400ce5fb4 0


And a typical dprice_n1.conf looks like this(all crucial info changed):

rpcuser=dpricerpc
rpcpassword=145tsergtergtdfgdfg356b
rpcallowip=127.0.0.1
rpcport=5551
server=1
listen=1
daemon=1
bind=[12.12.12.99:::1]:9990
logtimestamps=1
mnconflock=0
maxconnections=256
gen=0
masternode=1
masternodeprivkey=6wejdoijdpoijw[0df9we0idpodjkspjdcoijsdoicjspodjcQ

Should it work?
How can i check if the services are running after i run activate_masternodes_dprice?

Thanx
kopykat

**Comment by kopykatA** [comment]
What more info is needed?
WIth the above nothing works.

**Comment by marsmensch** [comment]
Your bind instruction is wrong. This is a code issue tracker, not a help desk. Please join the respective coins slack with questions how the config file has to look like. A lot of people (including me) use my scripts to install DPRICE nodes and it works.
