### ISSUE TITLE
Memetic masternode private key: what addres and port to provide?

### ISSUE THREAD

**Issue by Fibroblasto** [masternodes/vps#22]
I am trying to setup a MEME masternode in Vultr.com. To get the masternode private key and collateral address the Memetic wallet ask me to provide an address and port. What address and port should I provide? Here is the screenshot of the Memetic wallet asking tat informamation.

![xxx](https://user-images.githubusercontent.com/1661250/33184117-51893330-d07b-11e7-8ca9-625215b267b3.png)

**Comment by marsmensch** [comment]
The address and port of the mastertoad you just instaled on the VPS. Please join the community slack to ask questions about the format.
