### ISSUE TITLE
Renew BitSend

### ISSUE THREAD

**Issue by wfthkttn** [masternodes/vps#26]
Renew request: BitSend
------------------------------------------------------------------
- [BitSend](bitsend.info)
- [Btctalk](https://bitcointalk.org/index.php?topic=1370307)
- [GitHub](https://github.com/LIMXTEC/BitSend)
- [Working script](https://github.com/dArkjON/BSD-Masternode-Setup-1604) for current binaries

**Comment by marsmensch** [comment]
THAT LINKED SCRIPT IS TEH REAL HORROR,wtf :D

Updated the config to the new tag 74eca2872c81e0bf050d364bdc7e256242b76edc

The rest was already correct
