### ISSUE TITLE
Alqo Masternode "couldnt connect to server issue" 

### ISSUE THREAD

**Issue by ryang20001** [masternodes/vps#30]
Hello,

Followed the script and got everything finished. Issue I am coming up with after I activate the masternode on the VPS, I run the script to check it /usr/local/bin/alqo-cli -conf=/etc/masternodes/alqo_                   n1.conf getinfo and it gve me the following error 

error: couldn't connect to server

Must be missing one little part of the install but just not sure where. Any help would be appreciated

I assume the above error is also why I am getting a "error invalid IP address port 55500" when tring to start the masternode on the local wallet.

**Comment by benjamindell** [comment]
I am also getting this issue. Any help would be much appreciated.

**Comment by ryang20001** [comment]
I assume this script is no longer supported, going to try another solution

**Comment by creamcoin** [comment]
Same here , after vps reboot: error: **couldn't connect to server after check command:**

`/usr/local/bin/xxxd -conf=/etc/masternodes/xxx_n1.conf getinfo`
