### ISSUE TITLE
Permission denied to masternode configuration files

### ISSUE THREAD

**Issue by Ludiro** [masternodes/vps#32]
Hey!
I'm installing a Zcoin Masternode, and after having installed everything, when I try to access the configuration files to change the private key, I get "Permission denied"

Would like to know how to solve it, thank you!

**Comment by marsmensch** [comment]
https://medium.com/tales-from-the-crypt-o/zcoin-masternode-setup-a4c1d900c0af EDIT that config file. It doesn't execute very well.
