### ISSUE TITLE
incomplete installation documentation

### ISSUE THREAD

**Issue by babatundebusari** [masternodes/vps#47]
I see that in your installation guide here https://masternodes.github.io/vps/docs/masternode_vps.html

No mention of the coin configuration file on the cold wallet(desktop wallet)
For example on chain coin..this will be chaincoin.conf file

No mention of this file in the installation guide
Also the bind port number are wrong for chaincoin for example..chain coin should be 11994 but the code has it has something else

So many things wrong

**Comment by marsmensch** [comment]
The cold wallet part is out of scope. These script are about the masternode part. Changing the port is as simple as changing a config file within the conf directory, so you can stop whining now.
