### ISSUE TITLE
CRAVE not working

### ISSUE THREAD

**Issue by babatundebusari** [masternodes/vps#52]
./install.sh -p crave -c 2
 ███╗   ██╗ ██████╗ ██████╗ ███████╗███╗   ███╗ █████╗ ███████╗████████╗███████╗██████╗
 ████╗  ██║██╔═══██╗██╔══██╗██╔════╝████╗ ████║██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗
 ██╔██╗ ██║██║   ██║██║  ██║█████╗  ██╔████╔██║███████║███████╗   ██║   █████╗  ██████╔╝
 ██║╚██╗██║██║   ██║██║  ██║██╔══╝  ██║╚██╔╝██║██╔══██║╚════██║   ██║   ██╔══╝  ██╔══██╗
 ██║ ╚████║╚██████╔╝██████╔╝███████╗██║ ╚═╝ ██║██║  ██║███████║   ██║   ███████╗██║  ██║
 ╚═╝  ╚═══╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝   ╚═╝   ╚══════╝╚═╝  ╚═╝
                                                             ╚╗ @marsmensch 2016-2018 ╔╝
Script version v0.8.4, you picked: crave
************************* Installation Plan *****************************************

I am going to install and configure
=> 2 crave masternode(s) in version tags/v2.5.0.1
for you now.

You have to add your masternode private key to the individual config files afterwards

Stay tuned!

A logfile for this run can be found at the following location:
/tmp/nodemaster_18-01-24-1516766908_out.log

*************************************************************************************
* Validating network rules
* No proper swap, creating it
* Package installation!
* Checking out desired GIT tag: tags/v2.5.0.1
* Starting the compilation process for crave, stay tuned
+--------------------------------------------------------+
|                                                        |
|                                                        |
|                                                        |
|                          ......                        |
|                     .,;cloddoolc;'.                    |
|                   'codxkkO000OOkxdc'.                  |
|                .'cdkOKXXNNWWWWNNXKOd:'.                |
|              .,:lxOXNWWMMMMMMMMMWKNKkl;.               |
|             .;:;lkKWWWWWWWWMMWWWWKKKkd;.               |
|             .;;,,oKX0OkkKXNNNXK0O0KOo;...              |
|             .:,,co:.    .cxddl.   'oxc...              |
|             .,',c'       ;xl;'    ..',....             |
|              ..;o;    .':ol,.,'. ..,,....              |
|              .';x0dlldOXXo. .'ldc,.,;....              |
|               .:x0X00XKXO,   .,oO0kdo,....             |
|                .';:;lOOOO;...:;ckKkcc,..               |
|                   .';oOKXOlo0Xk:cl'                    |
|                  ..c:cOKXNK0XKKd,,'.                   |
|                 .',;::coxkkxdxdl;,'..                  |
|                 .',ldolllooolclccl'..                  |
|                  ..;ldx0XXXNXKK0x:..                   |
|                    .,lodOO0XK0Oxc..                    |
|                       .,::::;;;'.                      |
|                                                        |
|                                                        |
|                                                        |
|                                                        |
|                                                        |
+--------------------------------------------------------+
**make: makefile.unix: No such file or directory
make: *** No rule to make target 'makefile.unix'.  Stop.
cp: cannot stat 'craved': No such file or directory**
0:00:00
Adding new system user masternode
* Creating masternode directories
* Configuring firewall rules
* Firewall ufw is active and enabled on system startup
* (over)writing systemd config files for masternodes
 ███╗   ██╗ ██████╗ ██████╗ ███████╗███╗   ███╗ █████╗ ███████╗████████╗███████╗██████╗
 ████╗  ██║██╔═══██╗██╔══██╗██╔════╝████╗ ████║██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗
 ██╔██╗ ██║██║   ██║██║  ██║█████╗  ██╔████╔██║███████║███████╗   ██║   █████╗  ██████╔╝
 ██║╚██╗██║██║   ██║██║  ██║██╔══╝  ██║╚██╔╝██║██╔══██║╚════██║   ██║   ██╔══╝  ██╔══██╗
 ██║ ╚████║╚██████╔╝██████╔╝███████╗██║ ╚═╝ ██║██║  ██║███████║   ██║   ███████╗██║  ██║
 ╚═╝  ╚═══╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝   ╚═╝   ╚══════╝╚═╝  ╚═╝
                                                             ╚╗ @marsmensch 2016-2018 ╔╝
************! ALMOST DONE !******************************
There is still work to do in the configuration templates.
These are located at /etc/masternodes, one per masternode.
Add your masternode private keys now.
eg in /etc/masternodes/crave_n1.conf

=> All configuration files are in: /etc/masternodes
=> All Data directories are in: /var/lib/masternodes

last but not least, run /usr/local/bin/activate_masternodes_crave as root to activate your nodes.

**Comment by babatundebusari** [comment]
error message here

`make: makefile.unix: No such file or directory
make: *** No rule to make target 'makefile.unix'. Stop.
cp: cannot stat 'craved': No such file or directory`

**Comment by marsmensch** [comment]
This is a regression inherited from the codebase switch last week. Fixed with 30acb3a69e7a794df8b7a93efca46448ac1ae565

Update the nodemaster script with a git pull and you will receive the changes. Sorry for the issue!
