### ISSUE TITLE
CROWD installation broken

### ISSUE THREAD

**Issue by jpsoares** [masternodes/vps#58]
Crowdcoin installation finished with the following: 

 /bin/mkdir -p '/usr/local/bin'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c crowdcoind crowdcoin-cli crowdcoin-tx bench/bench_crowdcoin '/usr/local/bin'
libtool: install: /usr/bin/install -c crowdcoind /usr/local/bin/crowdcoind
libtool: install: /usr/bin/install -c crowdcoin-cli /usr/local/bin/crowdcoin-cli
libtool: install: /usr/bin/install -c crowdcoin-tx /usr/local/bin/crowdcoin-tx
libtool: install: /usr/bin/install -c bench/bench_crowdcoin /usr/local/bin/bench_crowdcoin
 /bin/mkdir -p '/usr/local/include'
 /usr/bin/install -c -m 644 script/bitcoinconsensus.h '/usr/local/include'
make[3]: Leaving directory '/root/vps/code/crowd/src'
make[2]: Leaving directory '/root/vps/code/crowd/src'
make[1]: Leaving directory '/root/vps/code/crowd/src'
make[1]: Entering directory '/root/vps/code/crowd'
make[2]: Entering directory '/root/vps/code/crowd'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 libbitcoinconsensus.pc '/usr/local/lib/pkgconfig'
make[2]: Leaving directory '/root/vps/code/crowd'
make[1]: Leaving directory '/root/vps/code/crowd'
0:18:20
COMPILATION FAILED! Please open an issue at https://github.com/masternodes/vps/issues. Thank you!

Installed as Root on a Vultr Ubuntu 16, with ipv6

**Comment by jpsoares** [comment]
fixed issue by updating crown.env file with the following
MNODE_DAEMON=${MNODE_DAEMON:-/usr/local/bin/crowdcoind}

**Comment by mangae** [comment]
Hi, sorry to bother you, but I am facing the same issue as you did. Can you please tell me where to find "crown.env" or "crowd.enc" file and how to apply changes to it?

Thanks

**Comment by jpsoares** [comment]
it's now fixed in master, you might have a different issue

**Comment by mangae** [comment]
This is what I am getting:
root/Crowdcoin/src# make
make[1]: Entering directory `/root/Crowdcoin/src'
  CXXLD    crowdcoind
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:381: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
/usr/include/boost/filesystem/operations.hpp:384: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[1]: *** [crowdcoind] Error 1
make[1]: Leaving directory `/root/Crowdcoin/src'
make: *** [all-recursive] Error 1

**Comment by jpsoares** [comment]
That's a different issue.
Some users are having the same issue on https://github.com/bitcoin/bitcoin/issues/6603

**Comment by mangae** [comment]
You are right, and I am running older Ubuntu ver
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

Thanks for help ;)
