### ISSUE TITLE
INNOVA IPV6 not suport ?

### ISSUE THREAD

**Issue by Dizz888** [masternodes/vps#6]
INNOVA IPV6 not suport ?
http://pixs.ru/showimage/Screenshot_8058864_28150058.png

the port can only use 14520
http://pixs.ru/showimage/Screenshot_7228629_28149166.png

I can not run the second master node

I did 2 master nodes. one node is working fine. second error NEW_START_REQUIRED”
what could be the problem ?

**Comment by marsmensch** [comment]
If the installation went through and the nodes activated initially, it's almost always a very specific problem where the coins bct thread or slack is your best bet. 

Also make sure you waited at least a coupleof hours, often gui wallets sometimes lagged and didn't show the correct status of the masternodes.

Please collect the following data. You will need it anyways when you are talking to the corresponding developers.

Working with "PURE" as example here, adapt accordingly for your selected crypto:

[ ] Your operating system:
[ ] The content of the masternode configuration file ( /etc/masternodes/pure_n1.conf ): 
[ ] The debug.log in the data dir ( /var/lib/masternodes/pure1 ): 

Definitely also check with the individual crypto community. Especially related to **any IPv6 related problems**. Some coins simply dont support it yet and i do currently
not work around that. There will be a fix, but it will take a couple of days to be released.

If the installation went through and the nodes activated initially, it's almost always a very specific problem where the coins bct thread or slack is your best bet.

**Comment by marsmensch** [comment]
The script is not yet novice-friendly. That's why i decided to implement a menu-guided version right now. Please give me 2-3 days to rewrite / refactor the scripts to incorporate the feedback so far and make it better for all of us.

Tooling to make troubleshooting easier will be included, too. Stay tuned, closing this issue for now.
