### ISSUE TITLE
5 MN's of different coins on one VPS?

### ISSUE THREAD

**Issue by KingSlayerMN** [masternodes/vps#64]
I have multiple masternodes with different coins.
Each on one VPS. 
I'd like to consolidate them to have 5 MN on one VPS.
Can I run the script multiple times on the same server? 
E.g. once for Innova and another time for Crowdcoin?

**Comment by KingSlayerMN** [comment]
Answer: Yes, can run multiple times

**Comment by Djeezuz** [comment]
I have a question about this....if I wish to set up multiple masternodes on one vps, do I need to change any of the commands on the main tab for each coin? Like do i need to give each coin its own user name or anything? (FYI, I have virtually no programmer background but am looking into setting up a masternode.)
