### ISSUE TITLE
Confused about IP addresses

### ISSUE THREAD

**Issue by manoucho** [masternodes/vps#66]
First of all thanks a million for this guide, it would have been impossible to set up the MNs without it.

I'm confused about how I can set up 2 MN on one Vultr instance with 1 IP each:
- in the .conf file in /etc/masternodes there is only a line for an IPv6 address. Does it need to be changed ?

- do I need to add IP addresses on the settings page of Vulture ? IPv4 ? IPv6 ?

Thanks a lot for the help

**Comment by knowself** [comment]
I just set that instance to be IPv6 enabled which is free on Vultr and then use the "-c" flag with argument 2 and you'll have two masternode instances with two IPv6 addresses in 5 minutes.

**Comment by manoucho** [comment]
Thanks so much. So no need for a second ipv4 address, right? As this one is not free on Vultr

**Comment by knowself** [comment]
Correct. I regularly host 10 Masternodes using IPv6 addresses on a Vultr instance with a single IPv4 address.

**Comment by manoucho** [comment]
Thanks. Very useful!
