### ISSUE TITLE
ARC IPV6 Problem 

### ISSUE THREAD

**Issue by Dizz888** [masternodes/vps#7]
goldminenode start-all

12:23:59
{
  "overall": "Successfully started 0 goldminenodes, failed to start 2, total 2",
  "detail": {
    "status": {
      "alias": "MN1",
      "result": "failed",
      "errorMessage": "Invalid IP address, goldminenode=5a2632c5919f411c55cacfcf3e4ff7d76fdde79bec47a42b1054e87320000b6c-0"
    },
    "status": {
      "alias": "MN2",
      "result": "failed",
      "errorMessage": "Invalid IP address, goldminenode=dba042f11f3648679f034a36d747c4437be65895efdbc8e97d25e78f7c788d9a-1"
    }
  }
}

++++++++++++

goldminenode.conf

MN1 [2001:19f0:6c01:76e:2004::1]:7209 6vyNcfuB8Q1xW7Dnuo5q9pSWDnKFc2yfBmjL5zkMSowLy8edGJN 5a2632c5919f411c55cacfcf3e4ff7d76fdde79bec47a42b1054e87320000b6c 0
MN2 [2001:19f0:6c01:76e:2004::2]:7209 6uZ51ymWqZ3ogJ9QHsGbMD58FZpZwX7ZQkVr8NMNjgsAjKtNuGQ dba042f11f3648679f034a36d747c4437be65895efdbc8e97d25e78f7c788d9a 1

what is the problem ?
do not support IPV6 ?

**Comment by marsmensch** [comment]
If the installation went through and the nodes activated initially, it's almost always a very specific problem where the coins bct thread or slack is your best bet. 

Also make sure you waited at least a coupleof hours, often gui wallets sometimes lagged and didn't show the correct status of the masternodes.

Please collect the following data. You will need it anyways when you are talking to the corresponding developers.

Working with "PURE" as example here, adapt accordingly for your selected crypto:

[ ] Your operating system:
[ ] The content of the masternode configuration file ( /etc/masternodes/pure_n1.conf ): 
[ ] The debug.log in the data dir ( /var/lib/masternodes/pure1 ): 

Definitely also check with the individual crypto community. Especially related to **any IPv6 related problems**. Some coins simply dont support it yet and i do currently
not work around that. There will be a fix, but it will take a couple of days to be released.

If the installation went through and the nodes activated initially, it's almost always a very specific problem where the coins bct thread or slack is your best bet.

**Comment by marsmensch** [comment]
The script is not yet novice-friendly. That's why i decided to implement a menu-guided version right now. Please give me 2-3 days to rewrite / refactor the scripts to incorporate the feedback so far and make it better for all of us.

Tooling to make troubleshooting easier will be included, too. Stay tuned, closing this issue for now.
