### ISSUE TITLE
Cream correct ports

### ISSUE THREAD

**Issue by creamcoin** [masternodes/vps#71]
Cream ports has been changed after latest update v1.2

https://github.com/masternodes/vps/blob/59ec87c18ba416ec33efd0f5cf498e397c408cc3/config/cream/cream.env#L3

`MNODE_INBOUND_PORT=${MNODE_INBOUND_PORT:-45066}`

New ports are:

```
Default Port: 45066
RPC Port: 45077
```

reference: https://github.com/creamcoin/CREAM-cryptocurrency

> # the Cream team
https://cream.technology
https://creamcoin.com/

**Comment by marsmensch** [comment]
Thanks for the pointer, done!
