### ISSUE TITLE
Raspberry Pi Support

### ISSUE THREAD

**Issue by bleedr** [masternodes/vps#75]
What about doing a version for Raspian?
I'm playing around with some master nodes and mostly they work exactly the same, except some missing libraries that need to be replaced with the right ones

**Comment by mhannigan** [comment]
Nobody uses Raspberry Pie. Save yourself some time and pay $5 for a VPS.

**Comment by marsmensch** [comment]
Sorry, i am not going to do that:
https://medium.com/@Marsmensch/why-raspberry-masternodes-suck-cc801070723e
