### ISSUE TITLE
DigitalPrice Masternode Error

### ISSUE THREAD

**Issue by perserker1** [masternodes/vps#76]
Hi, first thanks for your amazing work. I have no programming skills and no expertise in setting up a masternode. Your work helps me a lot. 

I have managed to setup a server via vultr.com and installed your repositories. The problem is, that i get an error when i want to start the DigitalPrice masternode. I think i've done everything right (i also pasted my private key in the config file). This is the error message ive got when i run this command "/usr/local/bin/activate_masternodes_dprice": 

Job for dprice_n1.service failed because a fatal signal was delivered causing the control process to dump core. See "systemctl status dprice_n1.service" and "journalctl -xe" for details.
root@masternodes:~# 

This are the error messages: 

--------------------------------
● dprice_n1.service - dprice distributed currency daemon
   Loaded: loaded (/etc/systemd/system/dprice_n1.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: core-dump) since Thu 2018-03-29 20:07:28 UTC; 1s ago
  Process: 2717 ExecStart=/usr/local/bin/digitalpriced -daemon -pid=/var/lib/masternodes/dprice1/dprice.pid -conf=/etc/masternodes/dprice_n1.conf -datadir=/var

Mar 29 20:07:28 masternodes systemd[1]: dprice_n1.service: Control process exited, code=dumped status=6
Mar 29 20:07:28 masternodes systemd[1]: Failed to start dprice distributed currency daemon.
Mar 29 20:07:28 masternodes systemd[1]: dprice_n1.service: Unit entered failed state.
Mar 29 20:07:28 masternodes systemd[1]: dprice_n1.service: Failed with result 'core-dump'.
--------------------------------
Mar 29 20:08:54 masternodes digitalpriced[2928]: EXCEPTION: N5boost16exception_detail10clone
Mar 29 20:08:54 masternodes digitalpriced[2928]: the options configuration file contains an 
Mar 29 20:08:54 masternodes digitalpriced[2928]: digitalprice in AppInit()
Mar 29 20:08:54 masternodes digitalpriced[2928]: terminate called after throwing an instance
Mar 29 20:08:54 masternodes digitalpriced[2928]:   what():  the options configuration file c
Mar 29 20:08:54 masternodes systemd[1]: dprice_n1.service: Control process exited, code=dump
Mar 29 20:08:54 masternodes systemd[1]: Failed to start dprice distributed currency daemon.
-- Subject: Unit dprice_n1.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit dprice_n1.service has failed.
-- 
-- The result is failed.
--------------------------------

Maybe you can help. 
Thanks in advance! Nassi

**Comment by marsmensch** [comment]
Works and compiles for me. Make sure you edit the config before starting the nodes.

It's only two keys:
`bind=[#NEW_IPv4_ADDRESS_FOR_MASTERNODE_NUMBER:::1]:9990`
eg 111.222.333.444:9990
`masternodeprivkey=HERE_GOES_YOUR_MASTERNODE_KEY_FOR_MASTERNODE_dprice_1`
your masternode privkey ;-)
