### ISSUE TITLE
Chaincoin installation issue

### ISSUE THREAD

**Issue by ballyc27** [masternodes/vps#77]
Hi,

I have a $5 vultr vps running on Ubuntu 16.04 (with IPv6 enabled).
The chaincoin installation seems to be working but after 16 minutes is fails (see attached picture).
I was trying to install 3 nodes. After putty root login, these are the commands I ran:

git clone https://github.com/masternodes/vps.git && cd vps
./install.sh -p chain -c 3

Can you help please?

Many thanks,
Richie.

p.s. I used your script to successfully install synx recently...so I know its good for that coin.
p.s. wicked script by the way...class!

![capture2](https://user-images.githubusercontent.com/18078397/38168296-2815bd8c-3540-11e8-8ea2-b36370cd0162.PNG)

**Comment by marsmensch** [comment]
it seems the chaincoin devs think moving their github repos around is a good idea 👎 

Fixed the repo url and config to
```
CODENAME=chain
MNODE_DAEMON=${MNODE_DAEMON:-/usr/local/bin/chaincoind}
MNODE_INBOUND_PORT=${MNODE_INBOUND_PORT:-11994}
GIT_URL=https://github.com/chaincoin-legacy/chaincoin.git
SCVERSION="tags/v0.9.3.3"
NETWORK_BASE_TAG="2022"
```
New installations working again now. Sorry for the inconvenience!

**Comment by ballyc27** [comment]
Nice, many thanks...all working perfectly now.
Massive script!
