### ISSUE TITLE
Is this a website script ?

### ISSUE THREAD

**Issue by jhonmicheal** [masternodes/vps#78]
I am not understanding if we can install this on website or where we can use this. Please help me 
Thanks

**Comment by ballyc27** [comment]
Hi,
I'm  not the author but perhaps my comment will help.
The script to to help you install nodes on a linux server. Other script may exist to installation using windows OS but these instruction for linux are very good.
As the profitability of running a node can depend on a low cost server, the script author recommends vultr.com. This is the best option.
Hope this helps...

**Comment by marsmensch** [comment]
Check these articles to get started:
https://medium.com/tales-from-the-crypt-o/install-any-masternode-coin-with-nodemaster-f6607221d0bf
https://medium.com/tales-from-the-crypt-o/the-10-minute-masternode-setup-99bdb8d57e39

@ballyc27 Thanks for jumping in ;-)
