### ISSUE TITLE
Galactrum old version

### ISSUE THREAD

**Issue by naylordl** [masternodes/vps#83]
The galactrum version that is in the install is version v1.1.4 and the most up to date one is v1.1.6. I tired to change the galactrum.env file to reflect the newer version, but it failed on compilation.

Very soon (block 90000) the rewards are re-adjusted in favor of masternodes and this update has something to do with that.

**Comment by mthalmei** [comment]
I created a pull request #84 to update Galactrum to version 1.1.6.
Unfortunately the v1.1.6 tag is not correct. I contacted the developers but they are not interested in changing the tag. So we can just use the correct commit directly.

**Comment by naylordl** [comment]
Replacing v1.1.4 in the environment file with 8c465e0 seems to work. Thanks!
