### ISSUE TITLE
Does CROWN SN work ok with IPv6 addresses ?

### ISSUE THREAD

**Issue by ballyc27** [masternodes/vps#86]
In relation to CROWN SN, does this work ok with IPv6 addresses?
When I enter the IPv6 address (see below picture), I get a popup telling me to not include the port number. I guess, it see the ":" and thinks there is a port added.
To me, I'm entering the information correctly. Perhaps this coins only works with IPv4 addresses (meaning I may need to add additional IPv4 addresses to the VPS).
Can you confirm if this is correct please?

Many thanks.

![crown_issue](https://user-images.githubusercontent.com/18078397/39099272-decaea58-466f-11e8-94c9-c7814a732b07.jpg)

**Comment by marsmensch** [comment]
Afaikr CRW SNs+MNs only support IPv4. The script does work w/ IPv4. To enable that, just add the parameter "-n 4" to install.sh and fill in the IP address in the individual config files.
