### ISSUE TITLE
Cant commit

### ISSUE THREAD

**Issue by hodljt** [masternodes/vps#88]
I would like to contribute some new coins to your project unfortunately I am unable to push a branch.
I'm very familiar with git but have not used github before.

Password for 'https://hodljt@github.com':
remote: Permission to masternodes/vps.git denied to hodljt.
fatal: unable to access 'https://hodljt@github.com/masternodes/vps.git/': The requested URL returned error: 403

.git/config:

[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://hodljt@github.com/masternodes/vps.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[user]
        name = hodljt

thank you for any help.  hit me up here or twtr  @hodljt

**Comment by marsmensch** [comment]
You have to fork the repo and send me a pull requests ;-) 
https://yangsu.github.io/pull-request-tutorial/

If that's too hard, just paste the changes into a new issue please. Thank you!
