### ISSUE TITLE
Add support for Linda Masternode

### ISSUE THREAD

**Issue by larsen161** [masternodes/vps#92]
New coin request:
------------------------------------------------------------------
- https://bitcointalk.org/index.php?topic=2126041.0
- https://lindacoin.com/
- https://github.com/Lindacoin/Linda/
Optional and helpful (more likely i integrate fast):
- https://github.com/Lindacoin/Linda/releases/download/2.0.0.1/Unix.Lindad.v2.0.0.1g.tar.gz
- 33820
- 2.0.0.1

**Comment by marsmensch** [comment]
Linda is already supported for a while.
<img width="1201" alt="screen shot 2018-06-05 at 10 55 24" src="https://user-images.githubusercontent.com/82906/40965793-03cb3a4a-68af-11e8-822e-44e22f469d76.png">

**Comment by marsmensch** [comment]
Upgraded the default version to 2.0.0.1
