### ISSUE TITLE
Can't Connect to Unity Desktop

### ISSUE THREAD

**Issue by weidner** [masternodes/vps#98]
Hi --

I am a noob to Linux, so maybe this is a simple issue for someone who does know it.

I launched an AWS instance of Ubuntu 16.04 with Unity desktop installed (mainly because I'm a noob).  Connecting with Putty or VNC to the desktop worked fine.  

Then I ran the bash script to install masternodes.  Now I can connect with Putty, same as before.  But when I try with VNC viewer or via a webpage, I get a timeout no response.

I'm thinking some startup script that launches Unity was overwritten by the masternode script.

I am trying to learn my way around Linux, but if you can think of an obvious problem, I would appreciate you letting me know.

Thanks!
Dave

**Comment by marsmensch** [comment]
The firewall will block the VNC port for security reasons. Please don't install a GUI system to run a masternode. You can whitelist a specific ip for access though. Pointer:
https://askubuntu.com/questions/135619/allow-connections-to-vnc-server-only-from-specific-ip-addresses?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
